export const DOG_BREEDS = [
  "Affenpinscher","Afghan Hound","Airedale Terrier","Akita","Alaskan Malamute",
  "American Bulldog","American English Coonhound","American Eskimo Dog","American Foxhound",
  "American Hairless Terrier","American Leopard Hound","American Staffordshire Terrier",
  "American Water Spaniel","Anatolian Shepherd Dog","Appenzeller Sennenhund",
  "Australian Cattle Dog","Australian Kelpie","Australian Shepherd",
  "Australian Stumpy Tail Cattle Dog","Australian Terrier","Azawakh","Barbet","Basenji",
  "Basset Hound","Beagle","Bearded Collie","Beauceron","Bedlington Terrier",
  "Belgian Laekenois","Belgian Malinois","Belgian Sheepdog","Belgian Tervuren",
  "Bergamasco Sheepdog","Berger Picard","Bernese Mountain Dog","Bichon Frise",
  "Biewer Terrier","Black and Tan Coonhound","Black Russian Terrier","Bloodhound",
  "Bluetick Coonhound","Boerboel","Bolognese","Border Collie","Border Terrier","Borzoi",
  "Boston Terrier","Bouvier des Flandres","Boxer","Boykin Spaniel","Bracco Italiano",
  "Briard","Brittany","Broholmer","Brussels Griffon","Bull Terrier","Bulldog","Bullmastiff",
  "Cairn Terrier","Canaan Dog","Cane Corso","Cardigan Welsh Corgi","Carolina Dog",
  "Catahoula Leopard Dog","Caucasian Shepherd Dog","Cavalier King Charles Spaniel",
  "Central Asian Shepherd Dog","Cesky Terrier","Chesapeake Bay Retriever","Chihuahua",
  "Chinese Crested","Chinese Shar-Pei","Chinook","Chow Chow","Cirneco dell'Etna",
  "Clumber Spaniel","Cocker Spaniel","Collie","Coton de Tulear","Curly-Coated Retriever",
  "Czechoslovakian Vlcak","Dachshund","Dalmatian","Dandie Dinmont Terrier",
  "Danish-Swedish Farmdog","Doberman Pinscher","Dogo Argentino","Dogue de Bordeaux",
  "Dutch Shepherd","English Cocker Spaniel","English Foxhound","English Setter",
  "English Springer Spaniel","English Toy Spaniel","Entlebucher Mountain Dog",
  "Estrela Mountain Dog","Eurasier","Field Spaniel","Finnish Lapphund","Finnish Spitz",
  "Flat-Coated Retriever","French Bulldog","German Longhaired Pointer","German Pinscher",
  "German Shepherd Dog","German Shorthaired Pointer","German Wirehaired Pointer",
  "Giant Schnauzer","Glen of Imaal Terrier","Golden Retriever","Gordon Setter",
  "Grand Basset Griffon Vendéen","Great Dane","Great Pyrenees","Greater Swiss Mountain Dog",
  "Greyhound","Hamiltonstovare","Hanoverian Scenthound","Harrier","Havanese","Hokkaido",
  "Hovawart","Ibizan Hound","Icelandic Sheepdog","Irish Red and White Setter","Irish Setter",
  "Irish Terrier","Irish Water Spaniel","Irish Wolfhound","Italian Greyhound","Jagdterrier",
  "Japanese Akitainu","Japanese Chin","Japanese Spitz","Jindo","Kai Ken",
  "Karelian Bear Dog","Keeshond","Kerry Blue Terrier","Kishu Ken","Komondor","Kuvasz",
  "Labrador Retriever","Lagotto Romagnolo","Lakeland Terrier","Lancashire Heeler",
  "Lapponian Herder","Leonberger","Lhasa Apso","Lowchen","Maltese","Manchester Terrier",
  "Mastiff","Miniature American Shepherd","Miniature Bull Terrier","Miniature Pinscher",
  "Miniature Schnauzer","Mountain Cur","Mudi","Neapolitan Mastiff","Newfoundland",
  "Norfolk Terrier","Norwegian Buhund","Norwegian Elkhound","Norwegian Lundehund",
  "Norwich Terrier","Nova Scotia Duck Tolling Retriever","Old English Sheepdog","Otterhound",
  "Papillon","Parson Russell Terrier","Pekingese","Pembroke Welsh Corgi",
  "Peruvian Inca Orchid","Petit Basset Griffon Vendéen","Pharaoh Hound","Plott Hound",
  "Pointer","Polish Lowland Sheepdog","Pomeranian","Poodle","Porcelaine",
  "Portuguese Podengo","Portuguese Podengo Pequeno","Portuguese Pointer",
  "Portuguese Sheepdog","Portuguese Water Dog","Pudelpointer","Pug","Puli","Pumi",
  "Pyrenean Mastiff","Pyrenean Shepherd","Rafeiro do Alentejo","Rat Terrier",
  "Redbone Coonhound","Rhodesian Ridgeback","Romanian Mioritic Shepherd Dog","Rottweiler",
  "Russell Terrier","Russian Toy","Russian Tsvetnaya Bolonka","Saint Bernard","Saluki",
  "Samoyed","Schapendoes","Schipperke","Scottish Deerhound","Scottish Terrier",
  "Sealyham Terrier","Segugio Italiano","Shetland Sheepdog","Shiba Inu","Shih Tzu",
  "Shikoku","Siberian Husky","Silky Terrier","Skye Terrier","Sloughi",
  "Small Munsterlander","Smooth Fox Terrier","Soft Coated Wheaten Terrier","Spanish Mastiff",
  "Spanish Water Dog","Spinone Italiano","Stabyhoun","Staffordshire Bull Terrier",
  "Standard Schnauzer","Sussex Spaniel","Swedish Lapphund","Swedish Vallhund","Taiwan Dog",
  "Teddy Roosevelt Terrier","Thai Ridgeback","Tibetan Mastiff","Tibetan Spaniel",
  "Tibetan Terrier","Tornjak","Tosa","Toy Fox Terrier","Transylvanian Hound",
  "Treeing Walker Coonhound","Vizsla","Weimaraner","Welsh Springer Spaniel","Welsh Terrier",
  "West Highland White Terrier","Whippet","Wire Fox Terrier","Wirehaired Pointing Griffon",
  "Wirehaired Vizsla","Working Kelpie","Xoloitzcuintli","Yakutian Laika","Yorkshire Terrier",
] as const;

export const CAT_BREEDS = [
  "Abyssinian","American Bobtail","American Curl","American Shorthair","American Wirehair",
  "Balinese","Bengal","Birman","Bombay","British Longhair","British Shorthair","Burmese",
  "Burmilla","Chartreux","Chausie","Colorpoint Shorthair","Cornish Rex","Cymric","Devon Rex",
  "Donskoy","Egyptian Mau","European Burmese","Exotic Shorthair","Havana Brown","Himalayan",
  "Japanese Bobtail","Khao Manee","Korat","Kurilian Bobtail","LaPerm","Lykoi","Maine Coon",
  "Manx","Munchkin","Nebelung","Norwegian Forest Cat","Ocicat","Oriental Longhair",
  "Oriental Shorthair","Persian","Peterbald","Pixiebob","Ragdoll","Russian Blue","Savannah",
  "Scottish Fold","Selkirk Rex","Serengeti","Siamese","Siberian","Singapura","Snowshoe",
  "Somali","Sphynx","Thai","Tonkinese","Toyger","Turkish Angora","Turkish Van",
] as const;

export const HORSE_BREEDS = [
  "Akhal-Teke","Altai Horse","American Bashkir Curly","American Cream Draft","American Quarter Horse",
  "American Saddlebred","Andalusian","Anglo-Arabian","Appaloosa","Arabian","Ardennes","Austrian Warmblood",
  "Auxois","Azteca","Baise Horse","Balikun Horse","Barb","Belgian Draft","Belgian Warmblood","Berber",
  "Bhutia Pony","Bosnian Mountain Horse","Boulonnais","Brandenburger","Breton","Camargue","Canadian Horse",
  "Chincoteague Pony","Cleveland Bay","Colorado Ranger Horse","Comtois","Connemara Pony","Criollo",
  "Czech Warmblood","Dales Pony","Danish Warmblood","Dartmoor Pony","Dutch Warmblood","Estonian Native",
  "Exmoor Pony","Fell Pony","Finnhorse","Florida Cracker Horse","Freiberger","Friesian","Guizhou Horse",
  "Gypsy Vanner","Hackney","Hackney Pony","Haflinger","Hanoverian","Hequ Horse","Highland Pony",
  "Holsteiner","Hucul Pony","Icelandic Horse","Indian Marwari Pony","Irish Sport Horse",
  "Italian Heavy Draft","Jianchang Horse","Jutland","Karabakh","Karachai","Kathiawari","Kazakh Horse",
  "Kentucky Mountain Saddle Horse","Kiger Mustang","Kisber Felver","Kladruber","Knabstrupper",
  "Latvian Horse","Lipizzaner","Lusitano","Mangalarga Marchador","Mangalarga Paulista","Manipuri Pony",
  "Maremmano","Marwari","Mecklenburg Warmblood","Miniature Horse","Missouri Fox Trotter","Mongolian Horse",
  "Morgan","Muraközi","Mustang","New Forest Pony","Noriker","North Swedish Horse",
  "Norwegian Fjord","Oldenburg","Paint Horse","Paso Fino","Percheron","Peruvian Paso","Poitevin",
  "Pura Raza Española","Quarter Pony","Racking Horse","Rhenish German Coldblood","Rocky Mountain Horse",
  "Russian Don","Schwarzwälder Kaltblut","Selle Français","Shetland Pony","Shire","Sorraia",
  "Spiti Pony","Spotted Saddle Horse","Standardbred","Suffolk Punch","Swedish Warmblood",
  "Swiss Warmblood","Tennessee Walking Horse","Tersk","Thoroughbred","Tibetan Pony","Tokara Horse",
  "Trait du Nord","Trakehner","Ukrainian Riding Horse","Vladimir Heavy Draft","Welsh Pony",
  "Westphalian","Yakutian Horse","Yonaguni Horse","Yunnan Horse","Zaniskari Pony","Zangersheide",
  "Zhemaichu",
] as const;

export function getBreedsForSpecies(species: string): readonly string[] {
  switch (species) {
    case "dog": return DOG_BREEDS;
    case "cat": return CAT_BREEDS;
    case "horse": return HORSE_BREEDS;
    default: return [];
  }
}
